### ISSUE TITLE
Action with more than one parameter

### ISSUE THREAD

**Issue by z543** [hyperapp/logger#15]
in index.js line 18: var result = action(data)
it seem that action can only take one parameter ?

error when action with more than one parameter 
```js
const actions = {
    test1: (a, b)=>(state, actions) =>...
    test2: (state, actions) =>...
}
```

**Comment by okwolf** [comment]
@z543 you are correct. This is by design in Hyperapp, not something specific to the logger. See https://github.com/hyperapp/hyperapp#actions:

> An action is a unary function (accepts a single argument) expecting a payload.
