### ISSUE TITLE
Rename named export to withLogger.

### ISSUE THREAD

**Issue by jorgebucaran** [hyperapp/logger#18]
### Summary

Let's rename the named export to `withLogger` and this way, start a naming convention for all future higher-order-apps, e.g. `window.withGizmo`. I am not proposing we add a prefix to every package; I think `@hyperapp/html` should continue to be available as `window.html`.

### Related

- https://github.com/HyperappCommunity/hyperapp-debug/issues/1

**Comment by frenzzy** [comment]
Should it be named export then?
```js
import { withLogger } from '@hyperapp/logger'
```
vs
```js
// you already can use any of this:
import logger from '@hyperapp/logger'
import withLogger from '@hyperapp/logger'
import myFavoriteName from '@hyperapp/logger'
// why it is a breaking change?
```

**Comment by okwolf** [comment]
@frenzzy we could use a named export, although I’m not sure what else we would export. Maybe the default logger in case you wanted to wire it up to your custom `log` option?

The breaking part of the change is `window.withLogger` for UMD.

**Comment by jorgebucaran** [comment]
@okwolf I'm not sure either, but named exports  ftw on my book as well.

```jsx
import { withLogger } from '@hyperapp/logger'
```

**Comment by okwolf** [comment]
@jorgebucaran so then should we use `window.logger.withLogger`?

Or is there a way to make your named exports attach directly to `window.*` without being under a "namespace"? 🤔

**Comment by jorgebucaran** [comment]
@okwolf Yes.

ES6

```js
import { withLogger } from "@hyperapp/logger"
```
UMD
```js
const { withLogger } = logger // window.logger
```

> Or is there a way to make your named exports attach directly to window.* without being under a "namespace"? 🤔

~~Don't think so.~~ Clearly, I don't know what I am talking about.

**Comment by jorgebucaran** [comment]
What do you think @lukejacksonn?

**Comment by frenzzy** [comment]
> Or is there a way to make your named exports attach directly to window.* without being under a "namespace"? 🤔

[I do it](https://github.com/hyperapp/render/blob/v1.3.0/tools/build.js#L35) in `@hyperapp/render`, see [`extend: true` rollup option](https://rollupjs.org/guide/en#extend)

**Comment by jorgebucaran** [comment]
@frenzzy I don't understand. What's the point of that?

**Comment by jorgebucaran** [comment]
Ah, I see... you want `window.render` and `window.renderToString` when grabbing from a CDN, but when using ES modules, `import { render, renderToString } from "@hyperapp/render"`.

**Comment by okwolf** [comment]
@frenzzy @jorgebucaran  _should_ we do that though?

**Comment by jorgebucaran** [comment]
@okwolf I don't have a very strong opinion about this. To be honest, I don't know which one is better. 

This  looks more in line with how you use/import the function in a "real" context (using ES modules).
```js
const { withLogger } = logger 
// import { withLogger } from "@hyperapp/logger"
```

Using `extend: true` means you skip that and can go straight ahead to using `withLogger` in the code, which is pretty cool too.

But then, what if your library has a million functions? Are you going to pollute the `window` object with all of it? 

On the other hand, `withLogger` is unlikely to conflict with any other libraries used within a Hyperapp application. Or perhaps we should export `hyperappLogger` instead? 

So, many options... 😭

**Comment by jorgebucaran** [comment]
Whether we go for `hyperappLogger` or `logger`, one thing is for sure, we should use namespaces.

**Comment by frenzzy** [comment]
`render.render(app)` sounds strange, probably you mean this:
```js
window.hyperapp.h
window.hyperapp.app
window.logger.withLogger
window.render.withRender
window.render.renderToString
```
but we also may consider something like this:
```js
window.hyperapp.h
window.hyperapp.app
window.hyperapp.withLogger
window.hyperapp.withRender
window.hyperapp.renderToString
```
or maybe just:
```js
window.h
window.app
window.withLogger
window.withRender
window.renderToString
```

**Comment by jorgebucaran** [comment]
Do you know how to achieve this?

```js
window.hyperapp.h 
window.hyperapp.app
window.hyperapp.withLogger
window.hyperapp.withRender
window.hyperapp.renderToString
```

**Comment by frenzzy** [comment]
need to use `{ name: 'hyperapp', extend: true }`

**Comment by okwolf** [comment]
@frenzzy I'm not sure if I consider that an evil monkey patch or really clever 😆

**Comment by jorgebucaran** [comment]
@frenzzy @okwolf Sounds like a cool and safer way to use these modules when grabbing directly from a CDN like unpkg/hyperapp, unpkg/@hyperapp/logger, etc. But we'd want to make sure no official modules collide with hyperapp's `h` and `app`. Obviously, that won't happen, right? :P 

```js
import { h, app } from "hyperapp"
import { div, h1, button } from "@hyperapp/html"
```

becomes

```js
const { h, app } = hyperapp
const { div, h1, button } = hyperapp.html
```

**Comment by frenzzy** [comment]
yep, `{ name: 'hyperapp.NAME', extend: true }` also works, just a bit more bytes for each package:
```js
(global.hyperapp = global.hyperapp || {}, global.hyperapp.NAME = global.hyperapp.NAME || {})
```
...and still monkey patch of `window.hyperapp` namespace

**Comment by jorgebucaran** [comment]
**UPDATE**: We are using `camelCase`. 

Okay, we need to make a decision so I'll make it for us.

Notice this only affects CDN usage of these modules directly, so only things like jsFiddles and CodePens will need to be updated.

```
unpkg.com/hyperapp → hyperapp
unpkg.com/@hyperapp/logger → hyperappLogger
unpkg.com/@hyperapp/html → hyperappHtml
unpkg.com/@hyperapp/render → hyperappRender
```

**Comment by frenzzy** [comment]
Why they starts with a capital `H`? 😂

**Comment by jorgebucaran** [comment]
@frenzzy Yeah, I don't know about that either, but I think it's aesthetically more pleasing than camel case. 

# HyperappLogger
# hyperappLogger

**Comment by jorgebucaran** [comment]
@okwolf Let' go with HyperappLogger.

**Comment by okwolf** [comment]
@jorgebucaran so `window.HyperappLogger.withLogger`?

(Also should `@hyperapp/fx` be `window.HyperappFX`?)

**Comment by frenzzy** [comment]
```js
unpkg.com/hyperapp → Hyperapp
```
This is a breaking change, right?

**Comment by jorgebucaran** [comment]
@okwolf `window.hyperappLogger.withLogger` 🙏

**Comment by jorgebucaran** [comment]
# camelCase

**Comment by frenzzy** [comment]
And again why need to create a namespace if there only one export..
From user perspecrive this is much easier:
```js
const app = withLogger(hyperapp.app)
```
then this:
```js
const app = hyperappLogger.withLogger(hyperapp.app)
// or
const { withLogger } = hyperappLogger
const app = withLogger(hyperapp.app)
```
Don't you think?

**Comment by frenzzy** [comment]
If this is only for UMD build change which is mostly used on CodePen and jsFiddle. Why not to make it as easier for user as possible:
```js
window.h
window.app
window.withLogger
```
and it will remove the need to write unnecessary destructuring lines every time when you go to pen to check something..
~~`const { h, app } = hyperapp`~~
~~`const { withLogger } = hyperappLogger`~~
```js
withLogger(app)({}, {}, () => <h1>Hello</h1>, document.body)
```
..just one line

**Comment by jorgebucaran** [comment]
That would be too obscure. I much prefer a namespace.

```js
const { withLogger } = hyperappLogger
```

**Comment by okwolf** [comment]
@jorgebucaran updated my PR: #20.
